# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # or the latest stable version
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]
