data:
  feature_path: "data/features/v1_features.parquet"

training:
  model_type: "logistic_regression"
  params:
    max_iter: 1000
    penalty: "l2"

output:
  model_path: "models/model_v1.pkl"
  metrics_path: "models/metrics_v1.json"
